### PR TITLE
Use Postgres 12

### PR DESCRIPTION
**Pull request by anayrat**

### CODE REVIEW

**Comment by anayrat** [comment]
> I'm assuming that you didn't just create a "powa-archivist/12" directory followed by a "make" in the root directory for this PR? This should be the way to proceed, to avoid any mistake. I'll do some cleanup of this install_all.sql and document the way to add a new pg major version.
> 
> Do you want to update the PR once this is done or should I go ahead and also add the required files for pg12?

I wasn't aware of this procedure. I just look where there is file mentioning postgres-11 and replace `s/11/12/`.
I've done `make` but it seems nothing changed in my git repository. Maybe all the changed I've made were good?

**Comment by rjuju** [comment]
Doesn't `git status` show the whole directory as one untracked directory?

**Comment by anayrat** [comment]
Hum,  I tried with the files I created in this PR.

**Comment by rjuju** [comment]
Oh sorry I misunderstood your message.  Yes, it means that all your changes were good, except the install_all.sql files that should now be removed from the patch (see https://github.com/powa-team/powa-docker/commit/cec8d9effa2460372593df3c4995ca38458053b2)

**Comment by anayrat** [comment]
Ah ok, I removed and force-pushed

**Comment by rjuju** [comment]
Thanks, merged!

I'll try to build and upload the images now!

**Comment by rjuju** [comment]
All image are uploaded and seem to work as intended.  Thanks!

**Comment by anayrat** [comment]
Yeahh!

**Pull request merged**
